apiVersion: v1
kind: Pod
metadata:
 name: asterisk
spec:
 hostNetwork: true
 containers:
  - image: radersolutions/docker-ratel
    name: asterisk
    volumeMounts:
      - name: etc-asterisk
        mountPath: /etc/asterisk
      - name: var-spool-asterisk
        mountPath: /var/spool/asterisk
      - name: root
        mountPath: /root
 volumes:
  - name: etc-asterisk
    azureFile:
      secretName: storagesecret
      shareName: etc-asterisk
      readOnly: false
  - name: var-spool-asterisk
    azureFile:
      secretName: storagesecret
      shareName: var-spool-asterisk
      readOnly: false
  - name: root
    azureFile:
      secretName: storagesecret
      shareName: root
      readOnly: false
    mountOptions:
      - dir_mode=0700
      - file_mode=0600
      - uid=0
      - gid=0
      
      